- name: Install pacman packages
  become: yes
  become_user: root
  pacman:
    name: '{{item}}'
    state: present
  with_items:
    # Base packages
    - base
    - base-devel

    # VirtualBox guest additions
    - virtualbox-guest-modules-arch
    - virtualbox-guest-utils

    # XOrg
    - xorg-server
    - xorg-xinit
    - xorg-server-utils
    - xsel
    - xclip
    - arandr

    # XMonad
    - xmonad
    - xmonad-contrib
    - xcompmgr
    - unclutter
    - dmenu

    # Fonts
    - ttf-liberation

    # Terminal
    - rxvt-unicode
    - tmux

    # Tools
    - units
    - neovim
    - moreutils
    - wget
    - git
    - hub
    - ansible
    - fabric
    - openssh
    - htop
    - iftop
    - iotop
    - jq
    - unzip
    - ncdu
    - keepassx2
    - tcpdump
    - ngrep
    - wireshark-cli
    - bind-tools
    - httpie
    - the_silver_searcher

    # Java
    - jdk8-openjdk
    - maven

    # Docker
    - docker

    # Web surfing
    - dwb

    # NodeJS
    - nodejs
    - npm

    # Jupyter
    - jupyter
    - jupyter-notebook
    - python-pandas
    - python-matplotlib

    # Python
    - python2
    - python
    - flake8
    - python2-flake8

    # C++
    - cmake
    - gcc
    - clang
    - gdb

    # ASM
    - nasm

    # Ruby
    - ruby
    - ruby-bundler

    # Shell
    - bash-completion
    - shellcheck
  tags: [packages, pacman]

- name: Install python packages
  become: yes
  become_user: root
  pacman:
    name: '{{item[0]}}-{{item[1]}}'
    state: present
  with_nested:
    - [python, python2]
    -
      - setuptools
      - pip
      - virtualenv
      - requests
      - docopt
      - yaml
      - tox
  tags: [packages, python]

- name: Install pip2 packages
  become: yes
  become_user: root
  pip:
    name: '{{item}}'
    state: latest
    executable: /usr/bin/pip2
  with_items:
    - cqlsh==4.1.1
  tags: [packages, pip2]

- name: Install pip3 packages
  become: yes
  become_user: root
  pip:
    name: '{{item}}'
    state: latest
    executable: /usr/bin/pip3
  with_items:
    - proselint
  tags: [packages, pip3]

- name: Install Ruby gems
  become: yes
  become_user: root
  gem:
    name: '{{item}}'
    user_install: no
  with_items:
    - puppet-lint
    - mdl
  tags: [packages, gem]

- name: Install npm packages
  become: yes
  become_user: root
  npm:
    name: '{{item}}'
    global: yes
    state: latest
  with_items:
    - yarn
    - diff-so-fancy
    - create-react-app
  tags: [packages, npm]

- name: Create director ~/aur
  file:
    path: ~/aur
    state: directory
    mode: 0755
  tags: [packages, aur]

- name: Install AUR packages
  aur:
    name: '{{item}}'
    dir: ~/aur
  with_items:
    - cower
    - pacaur
    - hsetroot
    - fpp-git
    - google-cloud-sdk
    - leiningen
    - intellij-idea-ce
    - icdiff
    - ttf-ms-fonts
  tags: [packages, aur]

- name: Create symlink aliases in /usr/local/bin
  become: yes
  become_user: root
  file:
    src: '{{item.src}}'
    dest: '{{item.dest}}'
    state: link
  with_items:
    - {src: /usr/bin/nvim, dest: /usr/local/bin/vi}
    - {src: /usr/bin/nvim, dest: /usr/local/bin/vim}
